name = 'TTY Blocks'
license = 'MIT'
licenselink = 'https://github.com/owner/repo/LICENSE'
description = 'curses style shiiii'
homepage = 'https://github.com/signet-marigold/gohugo-theme-tty-blocks'

# If you have a running demo of the theme
demosite = 'https://owner.github.io/repo'

# Taxonomy terms
tags = ['blog']
features = ['']

# If the theme has a single author
[author]
  name = 'Alexander Hack'
  homepage = 'https://anhack.xyz'

